title: GEOG215
description: Summer 2024
theme: just-the-docs

url: https://jucardwell.github.io/geog215

search_enabled: false

nav_enabled: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
