title: GEOG215: Introduction to Spatial Data Science
description: Summer 2024, Instructor: Julia Cardwell
theme: just-the-docs

url: https://jucardwell.github.io/geog215

search_enabled: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
