title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://jucardwell.github.io/geog215

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
